# TODO Maps are being staticly loaded. Need to find a way to generate a map via gps coordinates.
# TODO See if we can replace "https://dl.dropboxusercontent.com" with "https://dl.dropboxusercontent.com" at complile time. Will make it easier to create sites.

# Domain
domain: http://17thAve.captivaterealestate.com

# Agent Info
agent-name: Anthony Navarro
agent-phone: 415 305 3291
agent-image-url: "https://scontent.fsnc1-1.fna.fbcdn.net/hphotos-xaf1/v/t1.0-9/25628_1334434155497_63081_n.jpg?oh=fa61357758046c6a02a9fec01b6cf8a5&oe=56BD096A"
agent-company: Coldwell Banker
agent-button-name-phone: "Anthony: 415 305 3291"
agent-website: "http://anthonysrealestate.com/"
# Optional Agent Info
agent-license: "BRE# 01491847"
agent-logo:

# Property Info
property-street-address: 1360A 17th Avenue
property-full-address: 1360A 17th Avenue, San Francisco, CA, 94122, United States
property-tag-line: "You're Home"
video-walkthrough-url: "https://dl.dropboxusercontent.com/s/s5kdx9e9wleroh8/1360A_17thAveWalkthrough.mp4?dl=0"
list-price:
sqft: 1008
number-of-beds: 1 Bed
number-of-baths: 1 Bath # TODO Fix alignment of baths in html
number-of-cars:
garden:

matterport-embed-url: "https://my.matterport.com/show/?m=KDgSw1Rw9SG"
property-description: Nearby schools include Woodside International School, Jefferson Elementary School and St Anne Elementary School. The closest grocery stores are Handy Deli, Lucca Food Store and Wah Sing Supermarket. Nearby coffee shops include Hollow, Starbucks and Cafe La Flore. Nearby restaurants include King of Noodles, Kitchen Kura and Underdog. 1360 17th AVE Unit 1360A is near Green Hairstreak Corridor - Aloha & Lomita, Grand View Park and Golden Gate Park. There are excellent bike lanes and the terrain has some hills. 1360 17th AVE Unit 1360A is very bikeable, biking is convenient for most trips.

# Showings
# showings: [
#   {
#     weekday: Saturday,
#     date: October 24,
#     time: "2:00-4:00PM"
#   },
#   { weekday: Sunday,
#     date: October 25,
#     time: "2:00-4:00PM"
#   },
#   {
#     weekday: Tuesday,
#     date:    October 27,
#     time:    "11:00-12:30PM"
#   },
#   {
#     weekday: Thursday,
#     date:    October 29,
#     time:    "5:30-6:30PM"
#   }
# ]

# Highlight TODO figure out a way to do two lists side by side with only one highlight collection. Add Columns to Highlights
# highlights-1: [
#   attribute: Incredible Light & Views,
#   attribute: Luxury Renovation,
#   attribute: Open Floor Plan,
#   attribute: 3-4BR/2.5BA,
# ]
# highlights-2: [
#   attribute: 11 Ft Ceilings,
#   attribute: Independent Garage,
#   attribute: "HOA Dues: $550/month",
#   attribute: "Sq Ft: 2300 per tax records",
# ]

# Neighboorhood
neighboorhood-background-image-url: "http://cdn.vidyard.com/thumbnails/custom/_H986cZ3gAbznd70KLoOsQ"
neighboorhood-name: Inner Sunset
neighboorhood-description: Besides the Inner Sunset’s rolling fog, there’s nothing bleak about this funky neighborhood. Bordering Golden Gate Park and home to University of California, San Francisco campus, the Inner Sunset remains close to nature without losing its big-city edge. Corner markets and a variety of ethnic eateries feed the local student population, whose laid-back presence creates a small-town feel just a quick ride away from the city’s center.
# Get GPS Coordinates from http://www.gps-coordinates.net/
map-longitude: -122.4749003
map-latitude: 37.7625308
map-zoom-level: 14

# Contact Section
contact-us-background-image-url: "https://hd1n2hd4y-res.cloudinary.com/image/upload/c_scale,w_800/post-63924.png"

# Photo Gallery
gallery-image-01: "https://dl.dropboxusercontent.com/s/jddho5ztnxfzwua/IMG_0599.JPG?dl=0"
gallery-image-02: "https://dl.dropboxusercontent.com/s/sjvhdvw3teyqn75/IMG_0622.JPG?dl=0"
gallery-image-03: "https://dl.dropboxusercontent.com/s/hokrs3p7v9ymab9/IMG_0701.JPG?dl=0"

gallery-image-04: "https://dl.dropboxusercontent.com/s/c7iwqup8fs0vjzk/IMG_0718.JPG?dl=0"
gallery-image-05: "https://dl.dropboxusercontent.com/s/cnd0dx5bx5jq1te/IMG_0716.JPG?dl=0"
gallery-image-06: "https://dl.dropboxusercontent.com/s/dx0aupnr7rpl95i/IMG_0740.JPG?dl=0"

gallery-image-07: "https://dl.dropboxusercontent.com/s/vx7g08v30kupakx/IMG_0747.JPG?dl=0"
gallery-image-08: "https://dl.dropboxusercontent.com/s/bx22z1r5e9rfo9v/IMG_0687.JPG?dl=0"
gallery-image-09: "https://dl.dropboxusercontent.com/s/7ihhek8px5ylild/IMG_0760.JPG?dl=0"

gallery-image-10: "https://dl.dropboxusercontent.com/s/50f954jdvv8nic7/IMG_0764.JPG?dl=0"
gallery-image-11: "https://dl.dropboxusercontent.com/s/hkkk5f7zg6fuacd/IMG_0755.JPG?dl=0"
